# Todos los centros deportivos donde se practique baloncesto y cuyo código postal sea 28025.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://DeportesMadridGroup2.es/Espacios/ontology/>
SELECT ?name
WHERE {
  ?centro ns:tieneCodigoPostal "28025".
  ?centro ns:tieneEquipamiento ?eq.
  ?eq ns:sePractica "basketball".
  ?centro ns:tieneNombre ?n
}


# Todos los centros deportivos donde se practique pádel y cumpla con las restricciones de coordenadas.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://DeportesMadridGroup2.es/Espacios/ontology/>
SELECT ?name
WHERE {
  ?centro ns:tieneLocalizacion ?d.
  ?d ns:tieneLongitud ?lon.
  ?d ns:tieneLatitud ?lat
  FILTER (?lon < -3.75)
  FILTER (?lat > 40.2)
  ?centro ns:tieneEquipamiento ?eq.
  ?eq ns:sePractica "paddle tennis".
  ?centro ns:tieneNombre ?n
}


# Todos los parques junto del distrito de Vicálvaro y su barrio
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd:<https://www.wikidata.org/wiki/>
PREFIX ns: <http://DeportesMadridGroup2.es/Espacios/ontology/>
PREFIX nsi: <http://DeportesMadridGroup2.es/Espacios/instances/>
PREFIX nseq: <http://DeportesMadridGroup2.es/Espacios/instances/Equipamiento/>
SELECT ?name ?barrio
WHERE {
  ?park a ns:ParquesJardines.
  ?park ns:estaEnDistrito "VICALVARO".
  ?park ns:estaEnBarrio ?barrio.
  ?park ns:tieneNombre ?name
}



# Todos los centros deportivos donde se practique tenis junto a su barrio y calle
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://DeportesMadridGroup2.es/Espacios/ontology/>
SELECT ?name ?barrio ?calle
WHERE {
  ?centro ns:estaEnBarrio ?barrio.
  ?centro ns:tieneEquipamiento ?eq.
  ?centro ns:tieneDireccion ?dir.
  ?dir ns:tieneCalle ?calle.
  ?eq ns:sePractica "tennis".
  ?centro ns:tieneNombre ?name
}
