# Perdón por no entregarlo antes, tuve problemas con Python que no detectaba el selectQuerry debido
# a ser una versión antigua, y no podía cambiar la versión que usaba Pycharm a la nueva hasta hace unos días
# -*- coding: utf-8 -*-
"""Task07.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1tV5j-DRcpPtoJGoMj8v2DSqR_9wyXeiE
**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
from rdflib.plugins.sparql import prepareQuery

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS

g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/resources/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""
ns = Namespace('http://somewhere#')
print("RDFlib")
for s, p, o in g.triples((None, RDFS.subClassOf, ns.Person)):
    print(s)
# ----------------
print("Sparql")
q = prepareQuery("""
    SELECT DISTINCT ?subclass WHERE{
    ?subclass rdfs:subClassOf ns:Person.
    }""", initNs={"ns":ns})
for e in g.query(q):
    print(e.subclass)

print("\n")
"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**"""
print("RDFlib")
for s, p, o in g.triples((None, RDF.type, ns.Person)):
    print(s)
# --------------
q = prepareQuery("""
    SELECT ?ind WHERE{
    ?subclass rdfs:subClassOf* ns:Person.
    ?ind rdf:type ?subclass.
    }""", initNs={"rdfs": RDFS, "rdf": RDF, "ns": ns})
print("Sparql")
for e in g.query(q):
    print(e.ind)
print("\n")

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**"""
print("RDFlib")
# lista_people = []
# for s, p, o in g.triples((None, RDF.type, ns.Person)):
#     lista_people += [(s, None)]
# for s, p, o in g.triples((None, RDFS.subClassOf, ns.Person)):
#     print(s)

for person, p, o in g.triples((None, RDF.type, ns.Person)):
    for s1, propertie, o1 in g.triples((person, None, None)):
        print(person, propertie)

for subclass, p, o in g.triples((None, RDFS.subClassOf, ns.Person)):
    for person, p1, o1 in g.triples((None, RDF.type, subclass)):
        print(person, subclass)
print("Sparql")
q = prepareQuery("""SELECT DISTINCT ?ind ?property WHERE{
    ?subclass rdfs:subClassOf* ns:Person.
    ?ind rdf:type ?subclass.
    ?ind ?property ?x} """, initNs={'ns':ns})

for e in g.query(q):
    print(e.ind, e.property)
q = prepareQuery("""
    SELECT ?ind ?subclass WHERE{
    ?subclass rdfs:subClassOf* ns:Person.
    ?ind rdf:type ?subclass.
    }""", initNs={"rdfs": RDFS, "rdf": RDF, "ns": ns})
for e in g.query(q):
    print(e.ind, e.subclass)
