# -*- coding: utf-8 -*-
"""Task06.ipynb
=======
Copia de Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at

https://colab.research.google.com/drive/1OvDraSRQzzCAc4AqyGNufvmvF4MRFsrw
https://colab.research.google.com/drive/1NeiN_69qOYYv_WBRhyIlPEDfXXojusNw

**Task 06: Modifying RDF(s)**
"""

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2022-2023/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
# Visualize the results
g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
g.add((ns.Researcher, RDF.type, ns.Person))
for s, p, o in g:
  print(s,p,o)
# Visualize the results

# Visualize the results
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# TO DO
janeURI= ns.JaneSmith
g.add((janeURI, RDF.type, ns.Researcher))
# Visualize the results
#=======
# Visualize the results
g.add((ns.JaneSmith, RDF.type,ns.Researcher))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

# TO DO
#<<<<<<< HEAD
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
JaneSmith=Literal("Jane Smith")
Jane=Literal("Jane")
Smith=Literal("Smith")
g.add((janeURI, VCARD.FN, JaneSmith))
g.add((janeURI, VCARD.Given, Jane))
g.add((janeURI, VCARD.Family, Smith))
# Visualize the results
for s, p, o in g:
  print(s,p,o)



"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# TO DO
g.add((ns.University, RDF.type, ns.upm))
g.add((ns.JohnSmith, VCARD.Work, ns.upm))
# Visualize the results
#=======
# Visualize the results
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.JaneSmith, vcard.fullName, Literal("Jane Smith")))
g.add((ns.JaneSmith, vcard.given, Literal("Jane")))
g.add((ns.JaneSmith, vcard.familynames, Literal("Smith")))

for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# TO DO
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith,vcard.work,ns.UPM))
# Visualize the results
for s, p, o in g:
  print(s,p,o)