# -*- coding: utf-8 -*-
"""Copia de Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmwkaXeGtXSjl7lYPvg7bRlrrvR5_umq

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")
print("\n")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)
print("\n")

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
print("6.1")
NS = Namespace("http://somewhere#")
g.add((NS.University, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)
print("\n")

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
print("6.2")
NS = Namespace("http://somewhere#")
g.add((NS.Researcher, RDFS.subClassOf, ns.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)
print("\n")

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# TO DO
print("6.3")
NS = Namespace("http://somewhere#")
g.add((NS.JaneSmith, RDF.type, NS.Researcher))
# Visualize the results
for s, p, o in g:
  print(s,p,o)
print("\n")

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

# TO DO
print("6.4")
NS = Namespace("http://somewhere#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
XSD = Namespace("http://www.w3.org/2001/XMLSchema#")
g.add((NS.JaneSmith, VCARD.FN, Literal('Jane Smith', datatype=XSD.string)))
g.add((NS.JaneSmith, VCARD.Given, Literal('Jane', datatype=XSD.string)))
g.add((NS.JaneSmith, VCARD.Family, Literal('Smith', datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)
print("\n")

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# TO DO
print("6.5")
NS = Namespace("http://somewhere#")
NS1 = Namespace("http://property#")
XSD = Namespace("http://www.w3.org/2001/XMLSchema#")
g.add((NS.JohnSmith, NS1.worksAt, Literal('UPM', datatype=XSD.string)))
g.add((NS.UPM, RDF.type, NS.University))
# Visualize the results
for s, p, o in g:
  print(s,p,o)
print("\n")